Second review
kaitcham/vet_clinic pull request #2
Opened 2022-05-31 17:29 UTC by kaitcham

For this brach, I followed these [requirements](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_query_update_tables.md).

2022-05-31 17:52 UTC, DeliceLydia requested changes
## Hi @kaitcham, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 

## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

2022-05-31 17:52 UTC, DeliceLydia commented on queries.sql
> +SELECT * FROM animals;
- [ ] Here you should select `species` you can do `SELECT species from animals;`

2022-05-31 17:52 UTC, DeliceLydia commented on queries.sql
> +SELECT AVG(escape_attempts) FROM animals WHERE date_of_birth BETWEEN '1990-01-01' AND '2000-12-31';
- [ ] Please add a query where you are checking `Who escapes the most, neutered or not neutered animals?`

2022-06-01 09:52 UTC, Lordkaito approved these changes
Hi @kaitcham, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 11:00 UTC, merged